vim.api.nvim_set_var('nvim_tree_quit_on_open', 1)
vim.api.nvim_set_var('nvim_tree_git_hl', 1)
vim.api.nvim_set_var('nvim_tree_highlight_opened_files', 1)
vim.api.nvim_set_var('nvim_tree_auto_open', 1)
vim.api.nvim_set_var('nvim_tree_indent_markers', 1)
