FROM archlinux

COPY ./init.sh /usr/bin/dev_init_env
RUN chmod +x /usr/bin/dev_init_env

RUN pacman --noconfirm -Syu sudo base-devel git mold

# nvim
RUN pacman --noconfirm -Syu sway neovim lua-language-server bash-language-server ripgrep fd wl-clipboard helix man

# zsh
RUN pacman --noconfirm -Syu openssh \
    fish \
    grml-zsh-config \
    gnupg \
    zellij

# C/C++
RUN pacman --noconfirm -Syu gcc gdb llvm make ninja cmake

# Go
RUN pacman --noconfirm -Syu go gopls go-tools

# Js/TS
RUN pacman --noconfirm -Syu nodejs npm typescript typescript-language-server

# Dev dependencies
RUN pacman --noconfirm -S libxcursor libxrandr libxi pkgconf unzip


# zig 
run pacman --noconfirm -Syu wget qemu-base

run pacman --noconfirm -Syu clang

# bevy
run pacman --noconfirm -Syu libx11 alsa-lib

run pacman --noconfirm -Syu opencl-headers opencl-rusticl-mesa ocl-icd gitui btop
